# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example     # rootユーザーのパスワード
      MYSQL_DATABASE: motocataloguedb  # データベース名
      MYSQL_USER: develop              # アクセスする際のユーザー名
      MYSQL_PASSWORD: develop          #アクセスする際のパスワード
    ports:
      - 3306:3306  # コンテナ外部からアクセスできるようにする。(MySQLのデフォルトポート番号)